## Numpy Array operations

In [3]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing", arr[2:7])
print("With step", arr[1:8:2])
print("Negative indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
With step [2 4 6 8]
Negative indexing 8


In [8]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element", arr_2d[1, 2])
print("Entire row: ", arr_2d[1])
print("Entire col: ", arr_2d[:, 1])

Specific element 6
Entire row:  [4 5 6]
Entire col:  [2 5 8]


## Sorting

In [12]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D array by row", np.sort(arr_2d_unsorted, axis=1))

Sorted Array [1 1 2 3 4 5 6 9]
Sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row [[1 3]
 [1 2]
 [2 3]]


## Filter

In [4]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


## Filter with mask

In [16]:
mask = numbers > 5
print("Numbers greater than 5:", numbers[mask])

Numbers greater than 5: [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [7]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5) # it stores indices of the elements for which condition is true. mask also works the same way
print(where_result)
print("NP where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [10]:
condition_array = np.where(numbers > 5, numbers*2, numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]
